import { ResourceKey } from '@empire/shared';
import type { ResourceDefinition } from './types';

export const RESOURCES: ResourceDefinition[] = [
  {
    key: ResourceKey.COINS,
    name: 'Coins',
    description: 'Soft currency earned from play. Buys land, listings and rush timers.',
    kind: 'currency',
    raidable: false,
    maxLootBps: 0,
    baseStorage: 0, // wallet has no cap
    color: '#f2c14e',
    icon: 'coin',
  },
  {
    key: ResourceKey.GEMS,
    name: 'Gems',
    description: 'Premium currency. Bought with real money or awarded by quests.',
    kind: 'premium',
    raidable: false,
    maxLootBps: 0,
    baseStorage: 0,
    color: '#7dd3fc',
    icon: 'gem',
  },
  {
    key: ResourceKey.WOOD,
    name: 'Timber',
    description: 'Cut at lumber mills. The backbone of early construction.',
    kind: 'resource',
    raidable: true,
    maxLootBps: 2000,
    baseStorage: 4000,
    color: '#8b5e34',
    icon: 'timber',
  },
  {
    key: ResourceKey.STONE,
    name: 'Stone',
    description: 'Quarried rock used for walls, towers and heavy structures.',
    kind: 'resource',
    raidable: true,
    maxLootBps: 2000,
    baseStorage: 4000,
    color: '#9ca3af',
    icon: 'stone',
  },
  {
    key: ResourceKey.FOOD,
    name: 'Provisions',
    description: 'Grown on farms. Consumed when training and upkeeping troops.',
    kind: 'resource',
    raidable: true,
    maxLootBps: 2500,
    baseStorage: 5000,
    color: '#84cc16',
    icon: 'grain',
  },
  {
    key: ResourceKey.IRON,
    name: 'Iron',
    description: 'Smelted from ore. Required by advanced military structures.',
    kind: 'resource',
    raidable: true,
    maxLootBps: 1500,
    baseStorage: 2500,
    color: '#94a3b8',
    icon: 'ingot',
  },
  {
    key: ResourceKey.GOLD,
    name: 'Gold Ore',
    description: 'Rare ore refined into coins at the Treasury.',
    kind: 'resource',
    raidable: true,
    maxLootBps: 1000,
    baseStorage: 1500,
    color: '#eab308',
    icon: 'nugget',
  },
];

export const RESOURCE_BY_KEY = new Map(RESOURCES.map((r) => [r.key, r]));
