import { BuildingCategory, ResourceKey, UnitClass } from '@empire/shared';
import type { UnitDefinition } from './types';

export const UNITS: UnitDefinition[] = [
  {
    key: 'swordsman',
    name: 'Swordsman',
    description: 'Cheap frontline infantry. Attacks whatever is nearest.',
    unitClass: UnitClass.INFANTRY,
    hitpoints: 120,
    damage: 14,
    defense: 6,
    speed: 1.6,
    range: 1,
    attackCooldownMs: 900,
    trainCost: { [ResourceKey.FOOD]: 40 },
    trainSeconds: 18,
    population: 1,
    trainedAt: 'barracks',
    unlockAtBuildingLevel: 1,
    asset: {
      model: null,
      placeholder: { shape: 'box', color: '#c94f4f', accent: '#7a2222', scale: [0.6, 1.2, 0.6] },
      icon: 'sword',
      lod: { high: 25, medium: 60, low: 120 },
    },
  },
  {
    key: 'spearman',
    name: 'Spearman',
    description: 'Braces against cavalry. Deals bonus damage to mounted units.',
    unitClass: UnitClass.INFANTRY,
    hitpoints: 150,
    damage: 11,
    defense: 10,
    speed: 1.4,
    range: 1.6,
    attackCooldownMs: 1100,
    trainCost: { [ResourceKey.FOOD]: 55, [ResourceKey.WOOD]: 20 },
    trainSeconds: 24,
    population: 1,
    trainedAt: 'barracks',
    unlockAtBuildingLevel: 2,
    asset: {
      model: null,
      placeholder: { shape: 'box', color: '#c98a4f', accent: '#7a4c22', scale: [0.6, 1.3, 0.6] },
      icon: 'spear',
    },
  },
  {
    key: 'heavy_guard',
    name: 'Heavy Guard',
    description: 'Armoured wall-breaker with high hitpoints. Soaks tower fire.',
    unitClass: UnitClass.INFANTRY,
    hitpoints: 420,
    damage: 26,
    defense: 22,
    speed: 1.0,
    range: 1,
    attackCooldownMs: 1400,
    trainCost: { [ResourceKey.FOOD]: 180, [ResourceKey.IRON]: 30 },
    trainSeconds: 95,
    population: 4,
    trainedAt: 'barracks',
    unlockAtBuildingLevel: 6,
    preferredTargets: { [BuildingCategory.WALL]: 3, [BuildingCategory.DEFENSE]: 1.4 },
    asset: {
      model: null,
      placeholder: { shape: 'box', color: '#4f6bc9', accent: '#22377a', scale: [0.8, 1.5, 0.8] },
      icon: 'shield',
    },
  },
  {
    key: 'archer',
    name: 'Archer',
    description: 'Fires over ramparts. Fragile if a tower reaches it.',
    unitClass: UnitClass.RANGED,
    hitpoints: 80,
    damage: 18,
    defense: 3,
    speed: 1.5,
    range: 5.5,
    attackCooldownMs: 800,
    trainCost: { [ResourceKey.FOOD]: 60, [ResourceKey.WOOD]: 30 },
    trainSeconds: 30,
    population: 1,
    trainedAt: 'archery_range',
    unlockAtBuildingLevel: 1,
    asset: {
      model: null,
      placeholder: { shape: 'box', color: '#4fc98a', accent: '#227a4c', scale: [0.55, 1.15, 0.55] },
      icon: 'bow',
    },
  },
  {
    key: 'mage',
    name: 'Runecaster',
    description: 'Slow caster whose bolts splash across tightly packed structures.',
    unitClass: UnitClass.CASTER,
    hitpoints: 130,
    damage: 40,
    defense: 5,
    speed: 1.1,
    range: 4.5,
    attackCooldownMs: 2000,
    trainCost: { [ResourceKey.FOOD]: 220, [ResourceKey.GOLD]: 15 },
    trainSeconds: 150,
    population: 5,
    trainedAt: 'archery_range',
    unlockAtBuildingLevel: 6,
    preferredTargets: { [BuildingCategory.DEFENSE]: 1.6 },
    asset: {
      model: null,
      placeholder: { shape: 'cone', color: '#9b6bd6', accent: '#4b2f70', scale: [0.7, 1.5, 0.7] },
      icon: 'rune',
    },
  },
  {
    key: 'cavalry',
    name: 'Outrider',
    description: 'Fast flanker that dives for production buildings behind the line.',
    unitClass: UnitClass.CAVALRY,
    hitpoints: 260,
    damage: 30,
    defense: 12,
    speed: 3.2,
    range: 1,
    attackCooldownMs: 1000,
    trainCost: { [ResourceKey.FOOD]: 200, [ResourceKey.WOOD]: 60 },
    trainSeconds: 110,
    population: 4,
    trainedAt: 'stable',
    unlockAtBuildingLevel: 1,
    preferredTargets: { [BuildingCategory.PRODUCTION]: 2, [BuildingCategory.STORAGE]: 1.6 },
    asset: {
      model: null,
      placeholder: { shape: 'box', color: '#d6a76b', accent: '#70532f', scale: [1.1, 1.3, 0.7] },
      icon: 'horseshoe',
    },
  },
  {
    key: 'siege_ram',
    name: 'Battering Ram',
    description: 'Ignores everything but fortifications. Enormous damage to walls and towers.',
    unitClass: UnitClass.SIEGE,
    hitpoints: 700,
    damage: 90,
    defense: 30,
    speed: 0.7,
    range: 1.2,
    attackCooldownMs: 2400,
    trainCost: { [ResourceKey.WOOD]: 400, [ResourceKey.IRON]: 120 },
    trainSeconds: 300,
    population: 10,
    trainedAt: 'siege_workshop',
    unlockAtBuildingLevel: 1,
    preferredTargets: {
      [BuildingCategory.WALL]: 5,
      [BuildingCategory.DEFENSE]: 2.5,
      [BuildingCategory.CORE]: 1.5,
    },
    asset: {
      model: null,
      placeholder: { shape: 'box', color: '#6b5a3f', accent: '#332b1c', scale: [1.6, 1.4, 1.0] },
      icon: 'ram',
    },
  },
];

export const UNIT_BY_KEY = new Map(UNITS.map((u) => [u.key, u]));

/** Troops a brand-new empire starts with. */
export const STARTER_ARMY: { key: string; count: number }[] = [
  { key: 'swordsman', count: 10 },
  { key: 'archer', count: 5 },
];
